name: jazz101
description: A Jazz and a classic music player
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.2
  audio_video_progress_bar: ^0.11.0
  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.7
  rxdart: ^0.27.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/audio/
    - assets/arts/
    - assets/arts/ic_launcher.png
    
